### ISSUE TITLE
Can we avoid pinning pymbar to 3.0.3?

### ISSUE THREAD

**Issue by jchodera** [conda-forge/perses-feedstock#11]
Pinning `pymbar` to exactly 3.0.3 is causing some environment-solving headaches:
https://github.com/conda-forge/perses-feedstock/blob/master/recipe/meta.yaml#L44

Do we need to pin to this exact version, or can we enlarge this to `>=3.0.3`?

**Comment by mikemhenry** [comment]
I'll need to investigate, I know that some versions of pymbar had some issues with convergence and would throw an obtuse error.

**Comment by mikemhenry** [comment]
Fixed with https://github.com/conda-forge/perses-feedstock/pull/13
