### ISSUE TITLE
Recipe does not include arsenic

### ISSUE THREAD

**Issue by jchodera** [conda-forge/perses-feedstock#18]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The conda recipe should include the OpenFF [`arsenic`](https://anaconda.org/conda-forge/arsenic) package in the [run requirements](https://github.com/conda-forge/perses-feedstock/blob/main/recipe/meta.yaml#L25) since we use this in analysis of the benchmarks.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by mikemhenry** [comment]
Good catch! Opened a PR to fix this!
