### ISSUE TITLE
Don't depend on pymol-open-source

### ISSUE THREAD

**Issue by jchodera** [conda-forge/perses-feedstock#3]
`perses` does not require `pymol-open-source` to run---this is for a rarely-used optional feature.

If we depend on `pymol-open-source`, because there are no `osx` builds available, `perses` cannot be installed on `osx`:
![image](https://user-images.githubusercontent.com/3656088/120121143-d8eeee80-c16f-11eb-9da4-4ccb05f2ef89.png)

@mikemhenry : Can we remove this dependency and push a new build increment out?

**Comment by mikemhenry** [comment]
Fixed in #4
